title: Shubh Chatterjee # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)




  Shubh is a senior data science professional with 8+ years of experience in predictive modeling and data-driven problem-solving.
  He has solved business problems across Industries (Banking, Healthcare, Digital offers) using machine learning techniques and data-driven insights.
  <br><br>
  <a href="https://www.linkedin.com/in/shubrashankh-chatterjee/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
